apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-lend-rabbitmq
  namespace: smartlend
  labels:
    app: smart-lend-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-lend-rabbitmq
  template:
    metadata:
      labels:
        app: smart-lend-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - name: amqp
              containerPort: 5672
            - name: management
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: smartlend-secrets
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: smartlend-secrets
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_DEFAULT_VHOST
              valueFrom:
                configMapKeyRef:
                  name: smartlend-config
                  key: RABBITMQ_VIRTUAL_HOST
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 768Mi
              cpu: 500m
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "ping"]
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 20
            failureThreshold: 5
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rabbitmq-data
---
apiVersion: v1
kind: Service
metadata:
  name: smart-lend-rabbitmq
  namespace: smartlend
  labels:
    app: smart-lend-rabbitmq
spec:
  selector:
    app: smart-lend-rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
