eureka.client.enabled=false
spring.cloud.discovery.enabled=false

spring.datasource.url=${SPRING_DATASOURCE_URL:${LOAN_MANAGEMENT_DB_URL}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${LOAN_MANAGEMENT_DB_USERNAME}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${LOAN_MANAGEMENT_DB_PASSWORD}}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:smart-lend-redis}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

spring.rabbitmq.host=${RABBITMQ_HOST:smart-lend-rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

customer-service.url=${CUSTOMER_SERVICE_URL:http://customerservice:8006}
prediction-service.url=${PREDICTION_SERVICE_URL:http://predictionservice:8007}

jwt.secret=${JWT_SECRET}
