eureka.client.enabled=false
spring.cloud.discovery.enabled=false

spring.datasource.url=${SPRING_DATASOURCE_URL:${CUSTOMER_DB_URL}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${CUSTOMER_DB_USERNAME}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${CUSTOMER_DB_PASSWORD}}

spring.rabbitmq.host=${RABBITMQ_HOST:smart-lend-rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
