eureka.client.enabled=false
spring.cloud.discovery.enabled=false

spring.datasource.url=${SPRING_DATASOURCE_URL:${IDENTITY_DB_URL}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${IDENTITY_DB_USERNAME}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${IDENTITY_DB_PASSWORD}}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:smart-lend-redis}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

spring.rabbitmq.host=${RABBITMQ_HOST:smart-lend-rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

jwt.secret=${JWT_SECRET}

admin.default.email=${ADMIN_DEFAULT_EMAIL}
admin.default.password=${ADMIN_DEFAULT_PASSWORD}
admin.default.role=${ADMIN_DEFAULT_ROLE}
