eureka.client.enabled=false
spring.cloud.discovery.enabled=false

spring.datasource.url=${SPRING_DATASOURCE_URL:${PREDICTION_DB_URL}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${PREDICTION_DB_USERNAME}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${PREDICTION_DB_PASSWORD}}

spring.rabbitmq.host=${RABBITMQ_HOST:smart-lend-rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

currency.service.url=${CURRENCY_SERVICE_URL:http://currencyservice:8011}
customerservice.service.url=${CUSTOMER_SERVICE_URL:http://customerservice:8006}

jwt.secret=${JWT_SECRET}
