eureka.client.enabled=false
spring.cloud.discovery.enabled=false

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:smart-lend-redis}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

currency.api.url=${CURRENCY_API_URL}
currency.api.fallback-rate=${CURRENCY_FALLBACK_RATE}
currency.update.interval=${CURRENCY_UPDATE_INTERVAL}
