#!/usr/bin/env bash
# Phase 0 — namespace, ConfigMap, Secrets (run on Linux dev host)
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
K8S_BASE="${ROOT_DIR}/k8s/base"

source "${ROOT_DIR}/scripts/k3s-preflight.sh"
echo "==> Phase 0: SmartLend k3s bootstrap"
k3s_preflight

kubectl get storageclass | grep -q local-path || echo "WARN: local-path StorageClass not found"

kubectl apply -f "${K8S_BASE}/namespace.yaml"
kubectl apply -f "${K8S_BASE}/configmap.yaml"

# App secrets
if [[ ! -f "${K8S_BASE}/secrets.yaml" ]]; then
  echo "ERROR: ${K8S_BASE}/secrets.yaml not found."
  echo "  cp ${K8S_BASE}/secrets.example.yaml ${K8S_BASE}/secrets.yaml"
  echo "  Edit passwords, then re-run."
  exit 1
fi
kubectl apply -f "${K8S_BASE}/secrets.yaml"

# Auto-generate mysql-secrets.yaml from secrets.yaml (Bitnami chart requires specific key names)
_extract() {
  grep -E "^\s+${1}:" "${K8S_BASE}/secrets.yaml" | awk -F'"' '{print $2}' | head -1
}
ROOT_PASS="$(_extract MYSQL_ROOT_PASSWORD)"
IDENTITY_PASS="$(_extract IDENTITY_DB_PASSWORD)"
CUSTOMER_PASS="$(_extract CUSTOMER_DB_PASSWORD)"
PREDICTION_PASS="$(_extract PREDICTION_DB_PASSWORD)"
LOAN_PASS="$(_extract LOAN_MANAGEMENT_DB_PASSWORD)"

if [[ -z "${ROOT_PASS}" || -z "${IDENTITY_PASS}" ]]; then
  echo "ERROR: Could not parse passwords from ${K8S_BASE}/secrets.yaml"
  echo "  Ensure MYSQL_ROOT_PASSWORD / IDENTITY_DB_PASSWORD are set as double-quoted strings."
  exit 1
fi

cat > "${K8S_BASE}/mysql-secrets.yaml" << YAML
# Auto-generated by phase0-bootstrap.sh from secrets.yaml — do not edit manually
apiVersion: v1
kind: Secret
metadata:
  name: mysql-identity-secrets
  namespace: smartlend
type: Opaque
stringData:
  mysql-root-password: "${ROOT_PASS}"
  mysql-password: "${IDENTITY_PASS}"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-customer-secrets
  namespace: smartlend
type: Opaque
stringData:
  mysql-root-password: "${ROOT_PASS}"
  mysql-password: "${CUSTOMER_PASS}"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-prediction-secrets
  namespace: smartlend
type: Opaque
stringData:
  mysql-root-password: "${ROOT_PASS}"
  mysql-password: "${PREDICTION_PASS}"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-loan-management-secrets
  namespace: smartlend
type: Opaque
stringData:
  mysql-root-password: "${ROOT_PASS}"
  mysql-password: "${LOAN_PASS}"
YAML

echo "==> Generated mysql-secrets.yaml from secrets.yaml"
kubectl apply -f "${K8S_BASE}/mysql-secrets.yaml"

echo "==> Phase 0 complete"
