fullnameOverride: mysql-prediction
global:
  security:
    allowInsecureImages: true
image:
  registry: docker.io
  repository: bitnamilegacy/mysql
volumePermissions:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/os-shell
auth:
  database: predictionservice
  username: predictionservice
  existingSecret: mysql-prediction-secrets
primary:
  persistence:
    enabled: true
    size: 5Gi
    storageClass: local-path
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
